let movies = [
    {
        title: "Jill",
        genre: "Action",
        stock: "22",
        ratings: 4.5,
    },
    {
        title: "Eve",
        genre: "Thriller",
        stock: "13",
        ratings: 4.1,
    },
    {
        title: "Band of sisters",
        genre: "Action",
        stock: "20",
        ratings: 4.8,
    },
    {
        title: "Michael King",
        genre: "Action",
        stock: "20",
        ratings: 4.5,
    },
    {
        title: "Battle on buka street",
        genre: "Comedy",
        stock: "10",
        ratings: 4.0,
    },
    {
        title: "Boys over flower",
        genre: "Comedy",
        stock: "30",
        ratings: 4.9,
    },
    {
        title: "My daughter",
        genre: "Thriller",
        stock: "10",
        ratings: 4.5,
    },
    {
        title: "Gone girl",
        genre: "Thriller",
        stock: "20",
        ratings: 3.0,
    },
    {
        title: "Knock out",
        genre: "Action",
        stock: "30",
        ratings: 4.5,
    },
    {
        title: "Lockddown",
        genre: "Comedy",
        stock: "30",
        ratings: 4.5,
    },
    {
        title: "My maid",
        genre: "Comedy",
        stock: "30",
        ratings: 4.0,
    },
    {
        title: "Boss baby",
        genre: "Comedy",
        stock: "50",
        ratings: 3.9,
    },
    {
        title: "Money bag",
        genre: "Action",
        stock: "50",
        ratings: 3.0,
    },
    {
        title: "The heirs",
        genre: "Thriller",
        stock: "50",
        ratings: 4.5,
    },
    {
        title: "President Oose",
        genre: "Thriller",
        stock: "20",
        ratings: 2.5,
    },
    {
        title: "She's mine",
        genre: "Action",
        stock: "12",
        ratings: 3.2,
    },
    {
        title: "Love affairs",
        genre: "Comedy",
        stock: "30",
        ratings: 4.5,
    },
    {
        title: "Secrets",
        genre: "Thriller",
        stock: "14",
        ratings: 4.4,
    },
    {
        title: "Best friends",
        genre: "Comedy",
        stock: "5",
        ratings: 4.1,
    },
    {
        title: "The game",
        genre: "Action",
        stock: "10",
        ratings: 3.5,
    },
    {
        title: "Madam Alice",
        genre: "Thriller",
        stock: "50",
        ratings: 3.1,
    },
    {
        title: "The throne",
        genre: "Thriller",
        stock: "15",
        ratings: 4.6,
    },
    {
        title: "Marykay",
        genre: "Comedy",
        stock: "10",
        ratings: 3.5,
    }
];